added mocks and front end for last ten commits
ecvdbdx/git-view pull request #20
Opened 2021-11-26 16:36 UTC by Tristan-Autin

2021-11-26 16:39 UTC, antoinechassagne commented on src/pages/GitView.vue
> +    const { folderPath } = query;
Why not directly `const { folderPath } = route.query;` ?

2021-11-26 16:41 UTC, antoinechassagne commented on src/pages/GitView.vue
> +        <!-- <div class="line"></div> -->
Maybe we should remove this comment ?

2021-12-03 10:17 UTC, clemcode requested changes
I think that an acceptance criteria is not fullfiled : we have to specify the commit where the `HEAD` is, see #2

2021-12-10 13:28 UTC, clemcode approved these changes
👍

2021-12-10 13:46 UTC, felixbouveret approved these changes

2021-12-10 13:50 UTC, merged